//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSIST_BadDebtVendor_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bad_debt_placement_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bad_debt_placement_master()
        {
            this.bad_debt_placements = new HashSet<bad_debt_placements>();
        }
    
        public int id { get; set; }
        public string vendor { get; set; }
        public Nullable<System.DateTime> dateSent { get; set; }
        public string fileName { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string createdBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bad_debt_placements> bad_debt_placements { get; set; }
    }
}
