//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSIST_BadDebtVendor_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bad_debt_transactions
    {
        public int id { get; set; }
        public int placement_id { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
        public Nullable<decimal> transAmt { get; set; }
        public Nullable<decimal> curBal { get; set; }
        public string transCode { get; set; }
        public string transDesc { get; set; }
    
        public virtual bad_debt_placements bad_debt_placements { get; set; }
    }
}
