//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSIST_BadDebtVendor_Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bad_debt_placements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bad_debt_placements()
        {
            this.bad_debt_transactions = new HashSet<bad_debt_transactions>();
        }
    
        public int id { get; set; }
        public int master { get; set; }
        public string chsEntity { get; set; }
        public string accountNbr { get; set; }
        public string coid { get; set; }
        public string patName { get; set; }
        public Nullable<System.DateTime> patDOB { get; set; }
        public Nullable<System.DateTime> serviceDate { get; set; }
        public Nullable<decimal> originalBalance { get; set; }
        public string primaryIns { get; set; }
        public string secondaryIns { get; set; }
        public string tertiaryIns { get; set; }
        public string guarName { get; set; }
        public Nullable<System.DateTime> guarDOB { get; set; }
        public string guarSSN { get; set; }
        public string guarPhone { get; set; }
        public string guarCell { get; set; }
        public string guarAddress { get; set; }
        public string guarCity { get; set; }
        public string guarState { get; set; }
        public string guarZip { get; set; }
        public string guarOccupation { get; set; }
        public string guarEmployer { get; set; }
        public string guarEmpPhone { get; set; }
        public string guarEmail { get; set; }
        public Nullable<decimal> placementBalance { get; set; }
        public Nullable<System.DateTime> firstLetterDate { get; set; }
        public Nullable<System.DateTime> lastLetterDate { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual bad_debt_placement_master bad_debt_placement_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bad_debt_transactions> bad_debt_transactions { get; set; }
    }
}
