//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASSIST_BadDebtVendor_Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASSIST_Bad_Debt_Vendor_MgmtEntities : DbContext
    {
        public ASSIST_Bad_Debt_Vendor_MgmtEntities()
            : base("name=ASSIST_Bad_Debt_Vendor_MgmtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bad_debt_placement_master> bad_debt_placement_master { get; set; }
        public virtual DbSet<bad_debt_placements> bad_debt_placements { get; set; }
        public virtual DbSet<bad_debt_transactions> bad_debt_transactions { get; set; }
    }
}
